export const Users = [
  {
    id: 1,
    profilePicture: "assets/profile.jpg",
    username: "Animaw Yitayal",
  },
  {
    id: 2,
    profilePicture: "assets/coca.jpg",
    username: "Malefiya Belay",
  },
  {
    id: 3,
    profilePicture: "assets/gift.jpg",
    username: "Alex Abraham",
  },
  {
    id: 4,
    profilePicture: "assets/friends.jpg",
    username: "Awel Nuru",
  },
  {
    id: 5,
    profilePicture: "assets/coca.jpg",
    username: "Mekuria Tadesse",
  },
  {
    id: 6,
    profilePicture: "assets/friends.jpg",
    username: "Belay Belay",
  },
  {
    id: 7,
    profilePicture: "assets/profile.jpg",
    username: "Wubayehu Yitayal",
  },
  {
    id: 8,
    profilePicture: "assets/profile.jpg",
    username: "Asires Teka",
  },
  {
    id: 9,
    profilePicture: "assets/profile.jpg",
    username: "Gelila Haftom",
  },
  {
    id: 10,
    profilePicture: "assets/profile.jpg",
    username: "Bahilu Mola",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/profile.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/friends.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/profile.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/coca.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/profile.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/gift.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/profile.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/profile.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/profile.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/profile.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
